services:
  app:
    environment:
      NODE_ENV: production
      APP_PORT: ${APP_PORT:?APP_PORT is required}
      PROD_APP_PORT: ${PROD_APP_PORT:?PROD_APP_PORT is required}
      MARIADB_HOST: ${MARIADB_HOST:?MARIADB_HOST is required}
      MARIADB_PORT: ${MARIADB_PORT:?MARIADB_PORT is required}
      MARIADB_DATABASE: ${MARIADB_DATABASE:?MARIADB_DATABASE is required}
      MARIADB_USER: ${MARIADB_USER:?MARIADB_USER is required}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:?MARIADB_PASSWORD is required}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:?MARIADB_ROOT_PASSWORD is required}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT:?MINIO_ENDPOINT is required}
      MINIO_API_PORT: ${MINIO_API_PORT:?MINIO_API_PORT is required}
      MINIO_CONSOLE_PORT: ${MINIO_CONSOLE_PORT:?MINIO_CONSOLE_PORT is required}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:?MINIO_ROOT_USER is required}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:?MINIO_ROOT_PASSWORD is required}
      MINIO_BUCKET_IMAGES: ${MINIO_BUCKET_IMAGES:?MINIO_BUCKET_IMAGES is required}
    ports: !override
      - "${PROD_APP_PORT:?PROD_APP_PORT is required}:${PROD_APP_PORT:?PROD_APP_PORT is required}"
